### ISSUE TITLE
Horrible Dot product

### ISSUE THREAD

**Issue by 7Bpencil** [dankelley2/sharpPhysics#3]
In Vec2:

public static float DotProduct(Vec2 left, Vec2 right)
        {
            float[] a = {left.X, left.Y};
            float[] b = {right.X, right.Y};
            return a.Zip(b, (x, y) => x * y).Sum();
        }

Can be replaced by this:

public static float DotProduct(Vec2 left, Vec2 right)
        {
            return left.X * right.X + left.Y * right.Y;
        }

**Comment by dankelley2** [comment]
So it's that easy eh? Can't believe I didn't see that from the definition of "**dot product is the sum of the products of the corresponding entries of the two sequences of numbers**" Pardon my poor knowledge of textbook math, I never took > Algebra 2 (sophomore year high-school, we didn't have the most progressive math programs) and have been trying to learn more ever since.

Is this the case because we're limiting it to vec[2] instead of vec[6] etc? I'd think that's why all of the available dot product functions online are needlessly complicated.

**Comment by dankelley2** [comment]
Fixed this in commit 9042c4f
